### ISSUE TITLE
Add support for Cryptographic Parameters attribute

### ISSUE THREAD

**Issue by arvind5** [OpenKMIP/libkmip#34]
Current implementation does not support Cryptographic Parameters attribute such as cipher mode, padding mode, digest algorithm etc. These parameters are needed to describe the object that needs to be created. As an example, I would like to create a symmetric key with key algorithm AES, key length 256 and cipher mode GCM. I cannot do that today.

**Comment by PeterHamilton** [comment]
Hi @arvind5, my apologies on the severe delay on this issue. This year has been pretty crazy.

I've just finished the feature work supporting this and it should merge soon. Once the commit is linked to this issue, feel free to take a look at the new testing functions in `tests.c` for examples on how to create and use the `Cryptographic Parameters` attribute.
