### ISSUE TITLE
Add support for query, locate operations

### ISSUE THREAD

**Issue by rjew3ll** [OpenKMIP/libkmip#56]
I have already implemented this on an older branch.

From 1.2 spec: 

4.25 Query
This operation is used by the client to interrogate the server to determine its capabilities and/or protocol mechanisms. 

4.9 Locate
This operation requests that the server search for one or more Managed Objects, depending on the attributes specified in the request. All attributes are allowed to be used.

**Comment by PeterHamilton** [comment]
Hi @rjew3ll, thanks for filing this issue. I'm happy to review any code submissions you may have. Adding support for both `Query` and `Locate` would be a nice addition.

If your code is ready, go ahead and submit a pull request and I can take a look at it. Please follow the [Development guide](https://libkmip.readthedocs.io/en/latest/development.html) and be sure to include unit tests for any new functionality added.

**Comment by PeterHamilton** [comment]
@rjew3ll I'm going to go ahead and close this issue for now given your updates were merged in back in May. Let me know if there's anything else you need related to this issue.
